#!/usr/bin/env bash
# append-session-log.sh — auto-generuje session log dla bieżącego dnia
# Usage: scripts/append-session-log.sh [date YYYY-MM-DD]
# Domyślnie: dzisiejsza data.

set -euo pipefail

BASE_DIR="${BASE_DIR:-$(pwd)}"
DATE="${1:-$(date -u +%Y-%m-%d)}"

SESSIONS_DIR="$BASE_DIR/state/sessions"
mkdir -p "$SESSIONS_DIR"

LOG="$SESSIONS_DIR/${DATE}.md"
BC="$BASE_DIR/state/breadcrumbs.json"
FL="$BASE_DIR/state/feature_list.json"

[[ -f "$BC" ]] || { echo "[FAIL] breadcrumbs.json missing"; exit 1; }

# Wyciągnij eventy z dnia
EVENTS_TODAY=$(jq --arg d "$DATE" '[.[] | select(.ts | startswith($d))]' "$BC" 2>/dev/null || echo "[]")
EVENT_COUNT=$(echo "$EVENTS_TODAY" | jq 'length' 2>/dev/null || echo 0)

if [[ "$EVENT_COUNT" -eq 0 ]]; then
  echo "[SKIP] Brak eventów na $DATE — log niepotrzebny."
  exit 0
fi

# Project name z feature_list
PROJECT=$(jq -r '.project // "unknown"' "$FL" 2>/dev/null || echo "unknown")

# Actors distribution
ACTOR_DIST=$(echo "$EVENTS_TODAY" | jq -r 'group_by(.actor) | map({actor: .[0].actor, count: length}) | .[] | "\(.actor): \(.count) events"')

# First/last timestamps
FIRST_TS=$(echo "$EVENTS_TODAY" | jq -r '.[0].ts')
LAST_TS=$(echo "$EVENTS_TODAY" | jq -r '.[-1].ts')

# Sprinty in_progress / passed today
SPRINTS_INFO=""
if [[ -f "$FL" ]]; then
  SPRINTS_INFO=$(jq -r '.features[] | "  - Sprint \(.sprint): \(.name) [status: \(.status), iters: \(.iterations // 0)]"' "$FL" 2>/dev/null || echo "")
fi

# Git commits today
COMMITS_TODAY=""
if [[ -d "$BASE_DIR/.git" ]]; then
  COMMITS_TODAY=$(cd "$BASE_DIR" && git log --oneline --since="$DATE 00:00" --until="$DATE 23:59" 2>/dev/null || echo "(brak commitów)")
fi

# Pivots today
PIVOTS=$(echo "$EVENTS_TODAY" | jq -r '[.[] | select(.event == "pivot_executed")] | .[] | "  - Sprint \(.details.sprint): archived to \(.details.archived_branch)"' 2>/dev/null || echo "")
PIVOTS=${PIVOTS:-"(brak pivotów)"}

# Pisz log
cat > "$LOG" <<EOF
# Session log — $DATE

> Auto-generated by \`scripts/append-session-log.sh\` on $(date -u +%Y-%m-%dT%H:%M:%SZ).

## Session metadata

- **Date:** $DATE
- **Project:** $PROJECT
- **First event:** $FIRST_TS
- **Last event:** $LAST_TS
- **Total events:** $EVENT_COUNT

## Actors distribution

\`\`\`
$ACTOR_DIST
\`\`\`

## Sprints status (from state/feature_list.json)

$SPRINTS_INFO

## Pivots today

$PIVOTS

## Git commits today

\`\`\`
$COMMITS_TODAY
\`\`\`

## Notable events

\`\`\`
$(echo "$EVENTS_TODAY" | jq -r '.[] | select(.event | IN("sprint_passed", "pivot_executed", "escalation", "library_currency_checked", "goal_achieved")) | "[\(.ts)] \(.actor): \(.event)"' 2>/dev/null | head -20)
\`\`\`

## Links

- Breadcrumbs (filtered): \`jq '[.[] | select(.ts | startswith("$DATE"))]' state/breadcrumbs.json\`
- Feature list: \`state/feature_list.json\`
- Retrospectives this session: \`state/retrospectives/\`
- ADRs created: \`docs/adr/\`

## Notes (manual append below)

EOF

echo "[OK] Session log: $LOG"
ls -la "$LOG"
