#!/usr/bin/env bash
# init-docs-structure.sh — tworzy katalogi dokumentacji + sensible .gitignore
# Usage: scripts/init-docs-structure.sh
# Idempotent — jeśli katalogi już są, nie nadpisuje.

set -euo pipefail

BASE_DIR="${BASE_DIR:-$(pwd)}"

echo "=== Init docs structure in: $BASE_DIR ==="

# state/ (ephemeral)
mkdir -p "$BASE_DIR"/state/{prd,retrospectives,sessions,qa-reports,contracts,evidence,rubric/examples,archives}
echo "[OK] state/ subdirs created"

# docs/ (committable)
mkdir -p "$BASE_DIR"/docs/{adr,code-reviews,reports}
echo "[OK] docs/ subdirs created"

# Skeleton files (idempotent — touch only if absent)
[[ ! -f "$BASE_DIR/state/decision-log.md" ]] && cat > "$BASE_DIR/state/decision-log.md" <<'EOF'
# Decision Log

> Lekkie decyzje agentów (naming, wybory ad hoc). Architektoniczne → docs/adr/.
> Format: append-only.

EOF

[[ ! -f "$BASE_DIR/state/todo.md" ]] && cat > "$BASE_DIR/state/todo.md" <<'EOF'
# TODO (snapshot)

> Persistowany snapshot z TodoWrite. Agent dopisuje raz na iterację (NIE per krok).

## Sprint 1
- [ ] (nothing yet)

EOF

[[ ! -f "$BASE_DIR/state/blockers.md" ]] && cat > "$BASE_DIR/state/blockers.md" <<'EOF'
# Blockers — eskalacje do human

EOF

# .gitignore — state/ ephemeral, docs/ committable
GITIGNORE="$BASE_DIR/.gitignore"
if [[ ! -f "$GITIGNORE" ]] || ! grep -q "^state/$\|^state/\*\*" "$GITIGNORE" 2>/dev/null; then
  echo "" >> "$GITIGNORE"
  echo "# Agent Teams ephemeral state (per-session)" >> "$GITIGNORE"
  echo "state/" >> "$GITIGNORE"
  echo "# Keep docs/ committable for project knowledge" >> "$GITIGNORE"
  echo "[OK] .gitignore updated — state/ ignored, docs/ committable"
else
  echo "[SKIP] .gitignore already configured"
fi

# README pointing to docs/ convention
if [[ ! -f "$BASE_DIR/docs/README.md" ]]; then
  cat > "$BASE_DIR/docs/README.md" <<'EOF'
# Project documentation

Generated by `agent-teams-builder`. **Committable to repo** — kept across sessions.

## Structure

| Folder | What |
|---|---|
| `adr/` | Architecture Decision Records — `ADR-{NNNN}-{slug}.md` per arch decision |
| `code-reviews/` | Five-Axis Code Reviews — `CR-sprint-{N}-{slug}.md` per sprint passed |
| `reports/` | Final reports per project + special audits |

Ephemeral state lives in `state/` (gitignored). See `state/sessions/` for daily logs.
EOF
  echo "[OK] docs/README.md created"
fi

# Summary
echo ""
echo "=== ✅ Structure ready ==="
echo ""
echo "Ephemeral (state/):"
ls -la "$BASE_DIR/state/" | awk '{print "  " $9}' | grep -v "^$"
echo ""
echo "Committable (docs/):"
ls -la "$BASE_DIR/docs/" | awk '{print "  " $9}' | grep -v "^$"
echo ""
echo "Next steps:"
echo "  1. Planner: state/plan.md + state/prd/sprint-1.md"
echo "  2. Generator: docs/adr/ADR-0001-*.md per arch decision"
echo "  3. Evaluator: state/retrospectives/sprint-1.md po passed"
echo "  4. Validator: bash scripts/verify-documentation.sh"
